apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: default
data:
  index.html: |
    <!doctype html>
    <html>
      <head>
        <title>Docker Project</title>
      </head>
      <body>
        <p>Welcome to my Docker Project!</p>
        <p>Today's Date and Time is: <span id='date-time'></span></p>
        <script>
          var dateAndTime = new Date();
          document.getElementById('date-time').innerHTML = dateAndTime.toLocaleString();
        </script>
      </body>
    </html>
